name: CI/CD Java Spring
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PROJECT_NAME: jwt-validator
  REGION: us-east1
  DOCKERFILE_PATH: docker/Dockerfile
  REGISTRY_LOCATION: us-east1-docker.pkg.dev/sandbox-410701/sandbox

jobs:
  ci:
    name: Build, test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Java setup
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
      - name: Build with maven
        run: mvn clean verify

  ci_docker:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.REGISTRY_SA_KEY }}
      - name: Cloud sdk
        uses: google-github-actions/setup-gcloud@v1
      - name: Docker auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
      - name: Build
        run: docker build . -f ${{ env.DOCKERFILE_PATH }} -t ${{ env.REGISTRY_LOCATION }}/${{ env.PROJECT_NAME }}:${{ github.sha }}
      - name: Push
        run: docker push ${{ env.REGISTRY_LOCATION }}/${{ env.PROJECT_NAME }}:${{ github.sha }}